import Comments from '../Components/Comments';
import GalleryComponent from '../Components/GalleryComponent';
import { argentinaPhotos } from '../Photos-Data/Photos';
import './Argentina.css';

function Argentina() {
    return (
        <section className='argentina'>
            <h2>Argentina</h2>
            <a id='argentinaAnchor' href='#argentinaGalleryBelow'>(galería de fotos a final de página)</a>
            <iframe src="https://www.google.com/maps/embed?pb=!1m54!1m8!1m3!1d14199543.005429158!2d-60.254812!3d-29.670905!3m2!1i1024!2i768!4f13.1!4m43!3e0!4m5!1s0x95bcca3b4ef90cbd%3A0xa0b3812e88e88e87!2sBuenos%20Aires%2C%20Argentina!3m2!1d-34.6036844!2d-58.3815591!4m5!1s0x941bc3a35151b7f9%3A0xa5cd992cd587f206!2sSalta%2C%20Argentina!3m2!1d-24.782126899999998!2d-65.4231976!4m5!1s0x941f311369c3a61b%3A0x540e61c61f3a5d0c!2sCafayate%2C%20Salta%2C%20Argentina!3m2!1d-26.0730798!2d-65.976052!4m5!1s0x94223792d6c56903%3A0xf88d5b92b5c56527!2sSan%20Miguel%20de%20Tucum%C3%A1n%2C%20Tucum%C3%A1n%2C%20Argentina!3m2!1d-26.8082848!2d-65.2175903!4m5!1s0x9419c65b5f3bb7b7%3A0x50fbab0823a6b8d9!2sGalpon%2C%20Salta%2C%20Argentina!3m2!1d-25.382172!2d-64.6541297!4m5!1s0x94450c62a6f5f70b%3A0xf03ac86511c2cd6d!2sResistencia%2C%20Chaco%2C%20Argentina!3m2!1d-27.451862199999997!2d-58.985554699999994!4m5!1s0x94f6923af74e96dd%3A0xb4b8eeda942aae07!2sPuerto%20Iguaz%C3%BA%2C%20Misiones%2C%20Argentina!3m2!1d-25.597163499999997!2d-54.578599!5e0!3m2!1ses!2ses!4v1661937139359!5m2!1ses!2ses" width="600" height="450" style={{ border: 0 }} allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" title='Argentina Map'></iframe>
            <p>En Montevideo subí al bus hacia Buenos Aires. Con la compañia La Cacciola cuesta 29€. Ocho horas nocturnas de viaje, cena incluida y semi-cama. Llegué al Albergue Tango Hostel, en la avenida Boedo. 7€ la noche con desayuno incluido, además de amplias habitaciones y cocina. Se respiraba buen compañerismo y un bonito mestizaje.</p>
            <figure>
                <img src='https://laemancipaciondelvertigo.files.wordpress.com/2015/01/1.jpg' alt='Buenos Aires' />
                <figcaption>Buenos Aires</figcaption>
            </figure>
            <p>La conversión de moneda es fácil, puesto que el euro ronda los diez pesos. No hay casa de cambios, por lo que hay que canjear en la calle, siempre con cuidado. Tuve que insistir con los chicos con los que cambié pesos uruguayos a argentinos, pues mi cuenta salía el doble. Al final corrigieron y me dieron lo que correspondía.</p>
            <p>Es algo más barato que Uruguay. Respecto a España destaca el transporte público. Metro por 5 pesos (0’50€) transbordos incluidos y bus por 3’5 pesos con la tarjeta recargable. También el precio del tabaco baja mucho respecto a Europa, saliendo más de la mitad (20 pesos, 2€). La cultura también es asequible. Por ejemplo, la entrada más barata para ver a Les Luthiers sale 150 pesos. Es curioso que el billete de más valor que tendremos será de 100 pesos, sólo 10€.</p>
            <p>Estuve una semana en la enorme capital. Hasta tres millones de argentinos residen en Buenos Aires. Anduve mucho por el barrio La Boca, con el colorido y peculiar paseo de Caminito. Me gustó mucho el barrio San Telmo, de los más antiguos. También caminé por el barrio Chino y charlé con ancianos de la ciudad que me contaron su historia y la de la zona. Viví la muerte del fiscal Nisman por televisión casi en directo, caso que ha sobrecogido a todo el país, y que semanas después sigue en primera plana.</p>
            <p>Pensaba ir a Rosario pero cambié de rumbo gracias al autostop. Hice dedo desde el peaje de Buenos Aires y a la media hora me recogió un camionero que transportaba aceite. Me dejó cerca de Zarate, donde tuve que esperar como unas dos horas y media hasta que me levantaran unos vendedores ambulantes de fruta. Me invitaron a mate en su camioneta y me acercaron al peaje. Casi anochecía, y cuando estuve a punto de abandonar y trasnochar en el peaje, me levantó un amable camionero de autos. En Rosario iba a quedarme a las afueras y muy tarde, así que decidí seguir con él hasta Salta. Me recogió a las 20.30 y llegamos a las 17.00 del día siguiente. Más de veinte horas de viaje, más de 1500 kilómetros recorridos, durante los cuales me invitó a comer, a mate y a hoja de coca.</p>
            <figure>
                <img src='https://laemancipaciondelvertigo.files.wordpress.com/2015/02/autostop-buenos-aires.jpg' alt='Buenos Aires' />
                <figcaption>Camión autostop Buenos Aires</figcaption>
            </figure>
            <p>Me dejó en el Albergue Backpackers. 100 pesos la noche, bastante grande, muy bien acondicionado, excursiones, cenas baratas y desayuno incluido. Salta es una ciudad muy característica. Mucha montaña, altura y comidas asequibles. Las amistades que hice me invitaron a fernet y asado mientras veíamos el clásico Boca Juniors-River Plate. Quedé inmerso en historias de «quilombos» en «boliches», aprendí de sus «laburos» y de su genial «ya fue, no hay drama».</p>
            <p>Intenté hacer dedo hacia Cafayate pero tras hora y media no resultó. El Sol daba fuerte, me quedé sin sombra y decidí coger el bus. 130 pesos y tres horas y media de camino entre preciosos paisajes de la espectacular cordillera de los Andes. Cafayate es un pequeño pueblo perteneciente a Salta, mucho más artesanal, rodeado de imponentes montañas y con gran tradición de viñedos. Pude disfrutar por la noche de la Peña con cerveza salteña y vino local. Música en directo de folclore argentino, con el expresivo baile con pañuelos, la chacarera y la samba, baile-conga carnavalera incluida en la que me ví inmerso. Residí tres noches en el albergue Huayra Sanipi, por 80 pesos la noche desayuno incluido. Genial ambiente, música, asado, y una preciosa excursión a la grandiosa Quebrada de las conchas.</p>
            <p>De nuevo el autostop no funcionó. A la tarde subí a un bus camino de San Miguel de Tucumán por 20€. Casi seis horas de viaje entre montañas altísimas, otra vez con tremendos paisajes, muchas curvas y peligrosa niebla.</p>
            <figure>
                <img src='https://laemancipaciondelvertigo.files.wordpress.com/2015/01/dsc_3344.jpg' alt='Quebrada de las conchas' />
                <figcaption>Quebrada de las conchas</figcaption>
            </figure>
            <figure>
                <img src='https://laemancipaciondelvertigo.files.wordpress.com/2015/02/autostop-cafayate.jpg' alt='Autostop Cafayate' />
                <figcaption>Autostop Cafayate</figcaption>
            </figure>
            <p>Me acogió Alan en mi primera experiencia couchsurfing con seis viajeros más. Durante dos días en la ciudad subimos a almorzar típicas empanadas al cerro San Javier, visitamos el museo de la Independencia de Argentina y probé la local achilata entre cantos y guitarras. A las siete de la mañana puse rumbo y me levantó un joven camino de la universidad. Recorrí un poco, volví a hacer autostop y me recogieron dos chicos camino de Salta. Por el trayecto paramos en el museo Posta de Yatasto y tuvieron el gran detalle de invitarme a la entrada. Tras pasarnos mi cruce, volver, pinchar una rueda, esperar a que un camionero parara y nos prestara una llave e ir a una gomería por fin me dejaron en la ruta 16. Allí nos acumulamos haciendo dedo dos chicas, tres policías y yo. Pasada una hora rozando el anochecer por fin me levantó un profesor de biología y me trajo hasta El Galpón, un pueblo de siete mil habitantes, con un hostel caro y feo (130 pesos, sin desayuno, ni wifi, si quiera gente). Allí descansé y pude continuar al día siguiente mi ruta para Resistencia.</p>
            <p>En mi travesía, con todos los que me cruzo derrochan amabilidad, cercanía y simpatía. Me empapo de comidas típicas: asados, milanesas, empanadas, dulces de leche y matahambres. De cantar el Ríe Chinito de Perota Chingó. De que me confundan con un chileno, de que me nombren gallego y boludo, y de mencionarme a Sabina o Serrat. Empezó la verdadera locura del viaje. Justo cuando te conoces la zona y tienes confianza con las nuevas y buenas amistades (cada una con interesantes historias), tienes que partir y asumir que quizá no os volváis a cruzar. Y volver a verte en un sitio totalmente desconocido.</p>
            <figure>
                <img src='https://laemancipaciondelvertigo.files.wordpress.com/2015/02/accion-poetica-resistencia.jpg' alt='Acción Poética Resistencia' />
                <figcaption>Acción Poética Resistencia</figcaption>
            </figure>
            <p>Tras dormir unas diez horas me puse en marcha. Anduve a las afueras del municipio, y a los cinco minutos de levantar el pulgar me llevó un camionero. Me dejó a dos pueblos adelante, y a la media hora me recogió un mecánico. Sólo me pudo acercar al próximo pueblo. Pasó una hora hasta que me volvieron a levantar, y otra vez sólo iban al siguiente poblado. La calor era extrema y la de sesperación aparecía. Tras unas dos horas, me levantó un jornalero y, de nuevo, sólo iba al pueblo de al lado. Son villas muy pequeñitas, con gente muy honrada y educada. Tras otras dos horas intentándolo en el Quebrachal, nadie me levanta, y decido subir a un bus nocturno. Se retrasa una hora, apenas duermo y llegamos a Resistencia amaneciendo.</p>
            <p>El nombre de la ciudad parecía que quería decirme algo. Al llegar, me entero que me falla el contacto couchsurfing que tenía, y tras andar cuarenta minutos buscando un albergue barato que tenía apuntado, resulta que ya no existe. Empieza a llover, desayuno y busco wifi en la peatonal. Encuentro un hostel barato, me acerco a preguntar y está lleno, y los demás hospedajes son hoteles que salen de presupuesto. Ya por la tarde, decido comer y reposar un poco. Cansadísimo, algo frustrado y con una calor asfixiante, determino subir a un bus nocturno ya dirección Iguazú y así volver a ahorrarme la noche. Entonces, camino de la terminal. me encuentro de casualidad con un amigo que hice en Cafayate, el cual me invita a su casa. Conozco a su familia y me invitan a quedarme. Paso dos noches muy acogedoras, durante las cuales reposo y conozco la ciudad de las esculturas. Pruebo el tereré paraguayo y preparan unos exquisitos pescados (pacú y suribí), unas ricas empanadas y ensalada de frutas. Además me pagan el billete de bus hacia Iguazú. Eternamente agradecido.</p>
            <figure>
                <img src='https://laemancipaciondelvertigo.files.wordpress.com/2015/02/empanadas-pescado-caseras.jpg' alt='Empanadas caseras de pescado' />
                <figcaption>Empanadas caseras de pescado</figcaption>
            </figure>
            <p>A los diez minutos de trayecto paró el bus. Durante la ruta alguien lanzó una piedra y rompió una de las lunas, así que tienen que repararla. Cuarenta minutos después salimos. Llegué a Puerto Iguazú a las diez de la mañana y quedé con Ariel, el chico que me acogió en couchsurfing. Antes de irle a buscar a la salida del trabajo, visité el hito de las tres fronteras, desde donde se puede apreciar el río Iguazú y las fronteras de Brasil, Paraguay y Argentina. A la mañana siguiente salí a la excursión a las cataratas. Fueron cinco horas inolvidables. No me cansé de pasear por el parque, apreciar su flora y sus animales y, por supuesto, admirar las monumentales cataratas. Dependiendo del caudal, hay más o menos saltos, pero se calculan que hay más de 270 caídas. La mejor, la increíble Garganta del Diablo, con 80 metros de descenso. Además coincidí con un par de chicos ingleses que conocí en Buenos Aires y una pareja madrileña de Cafayate.</p>
            <figure>
                <img src='https://laemancipaciondelvertigo.files.wordpress.com/2015/01/cataratas-de-iguazc3ba.jpg' alt='Cataratas del Iguazú' />
                <figcaption>Cataratas del Iguazú</figcaption>
            </figure>
            <p>Por la noche conocí la noche de Iguazú con Ariel, que me levó de bares y discotecas. Un bonito ambiente mezclado entre los sesenta mil habitantes locales y todos los turistas que van y vienen cada día. Mi tercer y último día en Iguazú fue de descanso y de preparatorio para el siguiente destino, Paraguay.</p>

            <h3 id='argentinaGalleryBelow'>Galería de imágenes</h3>
            <GalleryComponent arrayPhotos={argentinaPhotos} />
            <Comments />
        </section>
    )
}

export default Argentina;