import { Link } from 'react-router-dom';
import { gardenRoutePhotos } from '../Photos-Data/Photos';
import './GardenRoute.css';
import GalleryComponent from "../Components/GalleryComponent";
import Comments from '../Components/Comments';

function GardenRoute() {
    const sectionCommentName = "gardenRoute";
    return (
        <section className='gardenRoute'>
            <h2>Ruta Jardín</h2>
            <a id='gardenRouteAnchor' href='#galleryGardenRouteBelow'>(galería de fotos a final de página)</a>
            <p>La Ruta Jardín es uno de los itinerarios más concurridos de Sudáfrica, uniendo Cape Town y Port Elizabeth en un recorrido de más de 700 kilómetros plagado de naturaleza.</p>
            <p>Decidí hacer este trayecto con el servicio «puerta a puerta» que ofrece Buzbus. Por 2200 rands puedes usar su bus durante una semana cuantas veces quieras, subir o bajar en el lugar de la ruta que te apetezca y parar en alguno de los hostels que operan con ellos. Los conductores son muy simpáticos (algunos en demasía) y el vehículo es muy cómodo, con cargadores para móviles y hasta wifi. Eso sí, justo después de contratarlo encontré la empresa alternativa, <a href='https://www.mzansi.travel/' target='_blank' rel='noreferrer'>Mzanzi</a>, mucho más barata pero más reciente y con menos publicidad.</p>
            <iframe className='gardenRoute' src="https://www.google.com/maps/embed?pb=!1m42!1m8!1m3!1d6801265.005164361!2d20.856605!3d-33.658971!3m2!1i1024!2i768!4f13.1!4m31!3e0!4m5!1s0x1dcc500f8826eed7%3A0x687fe1fc2828aa87!2sCdad.%20del%20Cabo%2C%20Sud%C3%A1frica!3m2!1d-33.924868499999995!2d18.4240553!4m5!1s0x1dce0b0126394dd7%3A0xd26afa6ef69fce0b!2sHermanus%2C%207200%2C%20Sud%C3%A1frica!3m2!1d-34.409200399999996!2d19.2504436!4m5!1s0x1dd61d81def6234f%3A0x51992275ebb3dfd3!2sWilderness%2C%20Sud%C3%A1frica!3m2!1d-33.994008199999996!2d22.5748481!4m5!1s0x1e7a55fe316c8f35%3A0xd73923e546801f08!2sBah%C3%ADa%20de%20Jeffreys%2C%20Sud%C3%A1frica!3m2!1d-34.0506714!2d24.9101544!4m5!1s0x1e7b290045ffd62b%3A0x86fd2337cd894226!2sPuerto%20Elizabeth%2C%20Sud%C3%A1frica!3m2!1d-33.9608369!2d25.6022423!5e0!3m2!1ses!2sbw!4v1661448242464!5m2!1ses!2sbw" width="600" height="450" style={{ border: 0 }} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade" title='Garden Route'></iframe>
            <p>Empecé por la ciudad de Hermanus. Llegué el primer día de Julio, coincidiendo con el mes que da entrada a la temporada de avistamiento de ballenas, aunque no tuve suerte con el clima. Tranquilidad es el adjetivo más adecuado para definir este lugar. Un marcado sendero de unas dos horas de ida y otras dos de vuelta permite pasear por toda su costa, con muchos bancos a cada poco tiempo con tremendas vistas. Además, la zona interior del pueblo está minada de tiendas de coleccionista y galerías de arte.</p>
            <img src='https://laemancipaciondelvertigo.files.wordpress.com/2018/07/hermanus-15.jpg' alt='Paisaje' loading="lazy" />
            <img src='https://laemancipaciondelvertigo.files.wordpress.com/2018/07/hermanus-12.jpg' alt='Banco' loading="lazy" />
            <p>Un curioso animal habita entre los peñascos de la costa. El damán de El Cabo o damán roquero, uno de los damanes más extendidos por toda África. Son bastante divertidos de ver y muy territoriales pero inofensivos.</p>
            <img src='https://laemancipaciondelvertigo.files.wordpress.com/2018/07/hermanus-31.jpg' alt='damán de El Cabo o damán roquero' loading="lazy" />
            <p>Como orinan siempre en el mismo lugar, en las rocas se amontonan cristales de carbonato cálcico, los cuales usaban tribus africanas para curar enfermedades como la histeria o la epilepsia. Es uno de los damanes más extendidos por toda África, del cual se dice que su especie (de orden Hyracoidea) está emparentada evolutivamente con los elefantes (orden Proboscidea).</p>
            <img src='https://laemancipaciondelvertigo.files.wordpress.com/2018/07/hermanus-81.jpg' alt='damán de El Cabo o damán roquero' loading="lazy" />
            <p>Mi segundo destino de la Ruta Jardín fue Wilderness, que cuenta con uno de los Parques Nacionales más visitados del país. Un sitio poco habitado, con escasos comercios y mayoría de apartamentos lujosos. La abandonada vía del tren de vapor Outeniqua Choo Tjoe cruza la ciudad en un trayecto que unía George y Knysna.</p>
            <img src='https://laemancipaciondelvertigo.files.wordpress.com/2018/07/wildernes-3.jpg' alt='vía del tren de vapor Outeniqua Choo Tjoe' loading="lazy" />
            <p>Me hospedé en <a href='https://wildfarmbackpackers.co.za/' target='_blank' rel='noreferrer'>Wild Farm</a>, un albergue-granja en lo alto del pueblo, pudiendo así otear bonitos paisajes durante la media hora de bajada. Otro de los atractivos es seguir el sendero paralelo al río, ideal para la observación de aves.</p>
            <img src='https://laemancipaciondelvertigo.files.wordpress.com/2018/07/wildernes-2.jpg' alt='Sendero junto al río' loading="lazy" />
            <p>Mi siguiente parada fue Jeffrey’s Bay, un pueblo que destaca por poseer la mezcla de corrientes del océano Atlántico con las del Índico, haciendo unas mareas muy características y representativas del movimiento surfero.</p>
            <p>Me alojé en <a href='https://jaybay.co.za/' target='_target' rel='noreferrer'>African Ubuntu Backpackers</a>. Ubuntu es un concepto africano tradicional, proveniente de las lenguas zulú y xhosa, una especie de ética entre las personas basada en la lealtad y las relaciones humanas.</p>
            <img src='https://laemancipaciondelvertigo.files.wordpress.com/2018/07/jeffreys-bay-3.jpg' alt='Gente haciendo deporte' loading="lazy" />
            <p>Coincidí por casualidad con las fechas del campeonato mundial de surf, por cuyo motivo estaba la playa abarrotada. Contemplé la final masculina y vi cómo se paraba la competición largo tiempo por el avistamiento de un tiburón cerca de la orilla. Esta bahía llena de mestizaje es idónea para aprender a surfear, seguir viajando gastronómicamente en <a href='https://www.ninas.co.za/' target='_balnk' rel='noreferrer'>Nina’s restaurant</a> o aprovechar el outlet de sus comercios de primeras marcas.</p>
            <img src='https://laemancipaciondelvertigo.files.wordpress.com/2018/07/jefreys-bay-5.jpg' alt='Jefrey’s Bay' loading="lazy" />
            <img src='https://laemancipaciondelvertigo.files.wordpress.com/2018/07/jefreys-bay-2.jpg' alt='Jefrey’s Bay' loading="lazy" />
            <p>Por último, visité Port Elizabeth, abreviada por todos como PE, uno de los mayores puertos del país. A pesar de su fama de ciudad peligrosa, su paseo por el muelle denota todo lo contrario. En este pequeño tramo podemos disfrutar de artistas callejeros repartidos entre un acuario, restaurantes y hasta un casino.</p>
            <img src='https://laemancipaciondelvertigo.files.wordpress.com/2018/07/port-elizabeth-51.jpg' alt='Port Elizabeth' loading="lazy" />
            <p>Lo mejor fue hacer amistades sudafricanas en el albergue. Me hablaron de su situación laboral, de la precariedad del país (un salario mínimo de 3500 rands al mes, 220€) y me invitaron a comer y pasear con ellos. También me alojé con un estudiante madrileño del cual pude aprender y comprender más acerca de la ciudad, así como beber cerveza en uno de los bares con más afluencia. En el parque de Central Hill disfruté de la famosa escultura de Nelson Mandela, The Voting Line, con el faro de fondo, junto a un grupo de niños jugando al rugby con una botella de plástico y un coro de mujeres ensayando su canto.</p>
            <img src='https://laemancipaciondelvertigo.files.wordpress.com/2018/07/port-elizabeth-21.jpg' alt='Vistas al mar' loading="lazy" />
            <p>Desde aquí podemos visitar las famosas reservas naturales de Shamwari Game, Donkin o Kragga Kamma. Yo opté por contratar un safari de un día en el <Link to='/mytrips/southafrica/southafrica/addo'>Parque Nacional de elefantes Addo</Link>.</p>
            <p>De Port Elizabeth fui hasta Johannesburgo mediante <a href='https://www.intercape.co.za/online-bus-tickets/book-now/' target='_blank' rel='noreferrer'>Intercape</a>, en un viaje de más de mil kilómetros, en total 15 horas por sólo 400 rands (26€). Allí sentí la inseguridad de la que hablan sobre Joburg, como comúnmente se la conoce, pues unos supuestos guardas de seguridad se acercaron ofreciéndome ayuda para acabar pidiéndome el móvil y dinero. No salí de la estación ya que mi bus hacia la aldea de Groot Marico salía en un par de horas. Una vez allí me alojé un par de días en la granja de intercambio <a href='https://www.happytoes.co.za/' target='_blank' rel='noreferrer'>Happy Toes</a>, un proyecto de permacultura y autogestión con muchos años a sus espaldas. Eso sí, muy alejado del pueblo, con riesgo de serpientes entre sus caminos y puentes basados en un tronco de árbol y un alambre.</p>
            <img src='https://laemancipaciondelvertigo.files.wordpress.com/2018/07/groot-marico21.jpg' alt='Groot Marico2.' loading="lazy" />
            <p>De noche, rugidos en la lejanía de leones enjaulados acompañaban un inmenso cielo estrellado. Desde allí crucé la frontera hasta mi primer destino en Botsuana, <Link to='/mytrips/southafrica/botsuana/gaborone'>Gaborone</Link>.</p>
            <h3 id='galleryGardenRouteBelow'>Galería de imágenes</h3>
            <GalleryComponent arrayPhotos={gardenRoutePhotos} />
            <Comments sectionCommentName={sectionCommentName} />
        </section >
    )
}

export default GardenRoute;