import './TravellingCheap.css';


function TravellingCheap() {
    return (
        <section className='travelCheap'>
            <h2>Cómo viajar barato</h2>
            <p>Viajar a coste cero no es tan difícil como creemos. Sólo tenemos que mentalizarnos y ser conscientes de que no va a ser una travesía igual que hayamos hecho antes. Nombraré consejos y páginas webs que he usado durante mi viaje de seis meses por europa occidental.</p>
            <h4>Hospedaje y comida</h4>
            <p><a href='https://www.couchsurfing.com/' target='_blank' rel='noreferrer'>Couchsurfing</a>. El turismo de sofá cada vez es más concurrido. Basta entrar con nuestro perfil de facebook, indicar nuestro destino y nos aparecerán muchas personas que están dispuestas a dejarnos dormir unos días en su casa y a enseñarnos la ciudad sin pedir nada a cambio.</p>
            <p><a href='https://wwoof.es/' target='_blank' rel='noreferrer'>WWOOF</a> es una organización que funciona globalmente. Se basa en el intercambio de trabajo en la permacultura. No se necesitan conocimientos previos, sólo ganas de aprender y ayudar. Pagando 20€ durante un año tendremos acceso al contacto de las granjas del país que elijamos. Por cuatro o cinco horas al día de trabajo, de lunes a viernes, los granjeros nos darán habitación y comida. Siempre es recomendable leer los comentarios respecto a las granjas y las condiciones de las mismas para dar con una en la que estemos cómodos, pero si no es así no hay sujeción de contrato alguna y podemos marcharnos cuando queramos, aunque en mi caso siempre quise quedarme más. También hay grupos por países en facebook en los que podemos consultar y localizar alguna granja sin pagar a la organización WWOOF.</p>
            <p><a href='https://www.workaway.info/' target='_blank' rel='noreferrer'>Workaway</a> funciona prácticamente igual que el <span>wwoofing</span>, pero además incluye otros trabajos, como niñero/a, recepcionista, intercambio de idiomas, informática, etc. En esta web podremos acceder a todos los hosts del mundo durante dos años pagando una sola vez 29€. Aquí no hay un horario generalizado, cada <span>host</span> tiene sus condiciones. También <a href='https://www.helpx.net/' target='_blank' rel='noreferrer'>Helpx</a> funciona de manera similar (nunca la llegué a usar).</p>
            <p>Otra opción es contactar personalmente con los albergues/hostels. En muchos de ellos se puede trabajar en recepción, limpiando y/o haciendo camas a cambio de alojamiento gratis, sólo es cuestión de escribirles y preguntar.</p>
            <p>En Francia existe un número, el 115, que al marcarlo contactamos con una centralita de la ciudad en la que estemos. Hablan español, francés e inglés y nos informarán de comedores (frecuentemente de monjas) y albergues sociales gratuitos. Podemos buscar información en cada país sobre estos centros. A unas últimas podemos esperar en el supermercado de la esquina a que tiren la comida (casi) caducada, una práctica usual en el país galo.</p>
            <h4>Transporte</h4>
            <p>La primera opción es el autostop. En todos los lugares del mundo te dirán que es muy difícil y que «la gente ha cambiado y ya no es como antes». Pero la verdad es que la mayoría que desaconseja usarlo nunca lo ha intentado, y está más extendido de lo que creemos. Sólo hay que tener paciencia y armarse de alimentos para un día. A mí me han llegado a recoger para cruzar la frontera de Francia yendo con un amigo, dos mochilas de 60L cada una y una guitarra. En Uruguay y Argentina es muy frecuente. La mejor opción es establecerse a la salida de una gasolinera o peaje y hacer un cartel con nuestro destino.</p>
            <p>Si eres español, en Italia y Francia no te multan en los trenes. Al menos a mí no me pasó. Cuentan que el papeleo para que la multa llegue a España es tal que los revisores no reparan tiempo en rellenar nada. Por ejemplo, en el trayecto Montpellier-Marsella (60€) siquiera pasó el revisor; subimos y bajamos del tren como si nada. Eso sí, en el tren de Marsella era imposible porque te exigían el billete antes de subir.</p>
            <p>En Italia, al pedirme el billete y contar que no tenía dinero, los revisores simplemente me invitaban a bajar, comentándome que no podía estar allí. Incluso uno me dijo con empatía que lo intentase en el siguiente. Así, desde que subes al tren y pasa el revisor y te echa, pueden pasar quince minutos o una hora, tiempo que vas avanzando. Con mucha paciencia y subiendo a un tren tras otro podremos llegar a nuestro destino a coste cero, o acercanos mucho a nuestro objetivo y que al final nos salga muy barato.</p>
            <p>Páginas como <a href='https://www.blablacar.es/' target='_blank' rel='noreferrer'>Blablacar</a>, <a href='https://amovens.com/es/' target='_blank' rel='noreferrer'>Amovens</a> o <a href='https://www.carpooling.es/' target='_blank' rel='noreferrer'>Carpooling</a> cada vez tienen más usuarios. Muchas personas tiene asientos libres para sus trayectos en coche y los ofrece a un precio bastante asequible. Siempre nos saldrá más barato que el bus, llegaremos antes y conoceremos mucha gente.</p>

        </section>
    )
}

export default TravellingCheap;